/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_physics_Obj */

#ifndef _Included_com_physics_Obj
#define _Included_com_physics_Obj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_physics_Obj
 * Method:    getX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    getY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    updateX
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_physics_Obj_updateX
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_physics_Obj
 * Method:    updateY
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_physics_Obj_updateY
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_physics_Obj
 * Method:    getOuterR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getOuterR
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    getInnerR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getInnerR
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getState
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    getMass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_Obj_getMass
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    changeState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_physics_Obj_changeState
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_Obj
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_physics_Obj_destroyNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
