/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_physics_LinearObj */

#ifndef _Included_com_physics_LinearObj
#define _Included_com_physics_LinearObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_physics_LinearObj
 * Method:    getvX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_LinearObj_getvX
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    getvY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_LinearObj_getvY
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    updateV
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_physics_LinearObj_updateV
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_physics_LinearObj
 * Method:    getXacc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_LinearObj_getXacc
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    getYacc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_physics_LinearObj_getYacc
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    updateAcc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_physics_LinearObj_updateAcc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_physics_LinearObj
 * Method:    getOri
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_physics_LinearObj_getOri
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    checkXTerminal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_physics_LinearObj_checkXTerminal
  (JNIEnv *, jobject);

/*
 * Class:     com_physics_LinearObj
 * Method:    checkYTerminal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_physics_LinearObj_checkYTerminal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
