/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_physics_FixedObj */

#ifndef _Included_com_physics_FixedObj
#define _Included_com_physics_FixedObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_physics_FixedObj
 * Method:    createNativeObject
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_com_physics_FixedObj_createNativeObject
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_physics_FixedObj
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_physics_FixedObj_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_physics_FixedObj
 * Method:    updatePos
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_physics_FixedObj_updatePos
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_physics_FixedObj
 * Method:    getNextX
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_physics_FixedObj_getNextX
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_physics_FixedObj
 * Method:    getNextY
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_physics_FixedObj_getNextY
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_physics_FixedObj
 * Method:    checkCollision
 * Signature: (Lcom/physics/Obj;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_physics_FixedObj_checkCollision
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_physics_FixedObj
 * Method:    boundCorrection
 * Signature: (DDDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_physics_FixedObj_boundCorrection
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_physics_FixedObj
 * Method:    collisionCorection
 * Signature: (Lcom/physics/Obj;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_physics_FixedObj_collisionCorection
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
