/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_spaceinvaders_gameEngine_Manager */

#ifndef _Included_org_spaceinvaders_gameEngine_Manager
#define _Included_org_spaceinvaders_gameEngine_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    createNativeObject
 * Signature: (IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_spaceinvaders_gameEngine_Manager_createNativeObject
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_spaceinvaders_gameEngine_Manager_destroyNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_spaceinvaders_gameEngine_Manager_update
  (JNIEnv *, jobject);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    drop1
 * Signature: (IIIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_spaceinvaders_gameEngine_Manager_drop1
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    drop2
 * Signature: (IIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_spaceinvaders_gameEngine_Manager_drop2
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    removeDead
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_spaceinvaders_gameEngine_Manager_removeDead
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_spaceinvaders_gameEngine_Manager
 * Method:    display
 * Signature: (IIII)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_spaceinvaders_gameEngine_Manager_display
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
